---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openebs-ci-backend
  name: openebs-ci-backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openebs-ci-backend
  template:
    metadata:
      labels:
        app: openebs-ci-backend
    spec:
      containers:
      - env:
        - name: TOKEN
          value: "E63xGAKPbh6wsWJGguyf"
        - name: DBHOST
          value: "http://10.100.218.232"
        - name: DBPORT
          value: "5432"
        - name: DBUSER
          value: "postgres"
        - name: DBPASS
          value: "2xWho5W0Zz"
        - name: DBNAME
          value: "postgres"
        name: openebs-ci-backend
        image: bhaskarjb/ci-e2e-dash-backend:1
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
            protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: openebs-ci-backend
  name: openebs-ci-backend
  namespace: default
spec:
  ports:
  - name: openebs-ci-backend
    port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30002
  selector:
    app: openebs-ci-backend
  type: NodePort     